name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fc3130bb2fe375d7360ac375f51830bb2afba40af6e4e6a8b1358efe57e3553"

[versions]
fabric = "0.18.5"
minecraft = "1.20.4"
