name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c816ed3cbe202f7f22aa9966211d902a817974bca2960479f7941f63d02beb64"

[versions]
fabric = "0.19.3"
minecraft = "1.20.4"
