hash-format = "sha256"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"

[[files]]
file = "config/yosbr/config/modmenu.json"

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true
