name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.16.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5310a5556fd5d749b811c36b0f1952f5b87da39cf1c6936224d34e8fdc6d1661"

[versions]
fabric = "0.18.5"
minecraft = "1.16.5"
