name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.16.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d30b78f82bbd86c543b9d379a816698c8a856a954b6af38f56220f926f123313"

[versions]
fabric = "0.18.5"
minecraft = "1.16.5"
