name = "Adrenaline"
author = "SkywardMC"
version = "26.1.4+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b0678fb9094ba78f0f776ebeb5a875f713b704674167290347ac7a5be35a3a4"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
