name = "Adrenaline"
author = "SkywardMC"
version = "26.4.0+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abf9fcf24e0671772466064aa76855a0846a49d0275b4c166f5471ad830ddac1"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
