name = "Adrenaline"
author = "SkywardMC"
version = "26.4.0+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1349e320abf5387035bc9e32b4136df0ff59b8d512482ae7c72a8f617c3e917"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
