name = "Adrenaline"
author = "SkywardMC"
version = "26.5.0+mc26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6297c65b7c017be64099a1fc20bcc9d0cd64d0241c2bac77e894aa0872be523c"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
no-internal-hashes = true
