name = "Adrenaline"
author = "SkywardMC"
version = "26.4.1+mc26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c2789cb20681a18d1bd1b68fbda934ead6002cce278db1f94290270b81f6a65"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
