name = "Adrenaline"
author = "SkywardMC"
version = "26.1.3+mc1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de52d3e387fed150bca9f96c01c1c068018d2148c8b20ded4496bde3c1e23611"

[versions]
fabric = "0.18.6"
minecraft = "1.21.11"
