name = "Adrenaline"
author = "SkywardMC"
version = "1.38.1+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c1ebf7f77fab856ad580205ff8517750a82404ff3945b65bec9ec8e43efe866"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
