name = "Adrenaline"
author = "SkywardMC"
version = "26.4.0+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4a052839993508fc533cef087344823b0733c0953112ea75d852b22e41ef263"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
