name = "Adrenaline"
author = "SkywardMC"
version = "26.3.1+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e2993a0b75f9659980e96aeece633353a4f5f5865dfbc1f2fdc8d58996f2061"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
