name = "Adrenaline"
author = "SkywardMC"
version = "26.4.0+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7334b85f337864ed2affd0d4bd2dc23f73835cb9bc349383f32938a2b528babd"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
