name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ca53f4104f0b63ded21517401a0da2389b7025d7db034bde225db044f7ee164"

[versions]
fabric = "0.18.5"
minecraft = "1.19.2"
