name = "Adrenaline"
author = "SkywardMC"
version = "1.37.0+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b72502348a48bb4765ee47ce17d55530f9068ac718e99ed686e5ad1e97b6168"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
