name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "864032415d137c5fd1ee8441e2bcd2f72058b779eb323ccabfa92a74adbc8d19"

[versions]
fabric = "0.18.5"
minecraft = "1.18.2"
