name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49235a3b42ccf840936e3344163b80787870e9942caf1ed22e0e6121d189dcc2"

[versions]
fabric = "0.18.4"
minecraft = "1.19.4"
