name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd57652c90650a9c753be231c2991a514d8afab011737b31eaed806bff9daa85"

[versions]
fabric = "0.18.5"
minecraft = "1.19.4"
