name = "Adrenaline"
author = "SkywardMC"
version = "1.32.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "180f24488ed38716cfd439d46f42e916fe671d773abc46e1c0517ab2f6f650b9"

[versions]
fabric = "0.17.3"
minecraft = "1.21.4"
