name = "Adrenaline"
author = "SkywardMC"
version = "26.1.3+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fdf40e2ba9f36072dc046666be372f0094452d80f6d5a3037ddf2da16e53dbe"

[versions]
fabric = "0.18.6"
minecraft = "1.20.1"
