name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9657d30bb076502a8030f7712b4bca731a7a72199a20ec23f7ae790bfee5f7e4"

[versions]
fabric = "0.18.5"
minecraft = "1.20.1"
