name = "Adrenaline"
author = "SkywardMC"
version = "26.4.1+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a77fbfd17892fb44c4f3e666970c3d963c821e504acaf5fa71cd8aef9c3e1636"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
