name = "Adrenaline"
author = "SkywardMC"
version = "26.5.1+mc26.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53d3cda3e34914c3bae2daea6d3cafa006c04cb7346d458ec7780d2e8fd739fd"

[versions]
fabric = "0.19.5"
minecraft = "26.3"

[options]
no-internal-hashes = true
